"""Sections 9-16: execution evidence, results, analysis, closing matter."""
from docbuild import (bullets, cap, code, figure, h1, h2, link, link_para, note,
                      para, table, FIG, SHOT)
from docx.shared import Pt

REPO = "https://github.com/tharuncoder676/SE-assigment"
RUN_URL = REPO + "/actions/runs/33625229403"
SHOTS_URL = REPO + "/tree/main/docs/screenshots"
CONSOLE_URL = REPO + "/tree/main/docs/console"


# =========================================================== section 9
def section9(doc):
    h1(doc, "9.  Execution Screenshots and Outputs", page_break=True)
    para(doc, "Every image in this section is a capture of the system actually running. The "
              "fifteen interface screenshots were produced by a Playwright script that drives the "
              "real browser through the real user journey against a live server, so no screen was "
              "posed. The console captures are verbatim output. Both sets are in the repository:")
    link_para(doc, "All 15 screenshots", SHOTS_URL)
    link_para(doc, "All 10 console transcripts", CONSOLE_URL)

    h2(doc, "9.1  The patient journey")
    figure(doc, SHOT / "01-registration.png", 10.4,
           "Screenshot 1 — Account creation. Client-side constraints mirror the server-side "
           "Pydantic schema, but the server validates independently; TC-03 proves a short "
           "password is rejected even if the browser is bypassed.")
    figure(doc, SHOT / "02-doctor-directory.png", 10.4,
           "Screenshot 2 — The directory immediately after registration, with the confirmation "
           "toast still visible. Eight seeded doctors across eight specialities.")
    figure(doc, SHOT / "04-speciality-filter.png", 10.4,
           "Screenshot 3 — The speciality filter applied. This is a server-side query "
           "(`GET /api/v1/doctors?speciality=Cardiology`), not client-side hiding.")
    figure(doc, SHOT / "05-available-slots.png", 10.4,
           "Screenshot 4 — Availability for the selected doctor. Only future, unbooked slots are "
           "returned; booked slots disappear from this list entirely.")
    figure(doc, SHOT / "07-booking-confirmed-toast.png", 10.4,
           "Screenshot 5 — Booking confirmed, with the reference returned by the API in the toast. "
           "The patient sees this before the notification has been written.")
    figure(doc, SHOT / "08-duplicate-booking-rejected.png", 10.4,
           "Screenshot 6 — The conflict path, captured live. The same slot was requested a second "
           "time and the server answered **HTTP 409 — Slot has already been booked**.")
    figure(doc, SHOT / "09-my-appointments.png", 10.4,
           "Screenshot 7 — Appointment history with references and status. The notification badge "
           "shows 2 unread, generated by the event bus.")
    figure(doc, SHOT / "10-notifications.png", 10.4,
           "Screenshot 8 — Notifications written by the background subscriber, not by the booking "
           "request itself.")
    figure(doc, SHOT / "11-appointment-cancelled.png", 10.4,
           "Screenshot 9 — After cancellation. The status pill changes and the slot returns to the "
           "available pool, which TC-17 verifies programmatically.")

    h2(doc, "9.2  The API contract")
    figure(doc, SHOT / "12-openapi-docs.png", 10.4,
           "Screenshot 10 — The OpenAPI document FastAPI generates from the Pydantic models. "
           "Because it is generated, it cannot drift from the implementation.")
    figure(doc, SHOT / "13-openapi-booking-endpoint.png", 10.4,
           "Screenshot 11 — The booking endpoint expanded, showing its schema and every documented "
           "response code including 409.")
    figure(doc, SHOT / "14-health-probe.png", 15.6,
           "Screenshot 12 — The liveness probe. Docker's HEALTHCHECK and Kubernetes probes consume "
           "this same endpoint.")
    figure(doc, SHOT / "15-prometheus-metrics.png", 9.4,
           "Screenshot 13 — Prometheus exposition served directly by the application, with no "
           "exporter sidecar.")

    h2(doc, "9.3  Test execution")
    figure(doc, FIG / "console-01-pytest.png", 14.6,
           "Console 1 — The full suite: 25 passed in 2.01 s. TC-16, the ten-thread booking race, "
           "is the seventh line.")
    figure(doc, FIG / "console-02-coverage.png", 13.0,
           "Console 2 — Statement coverage over the application package: 605 statements, 30 "
           "missed, 95%.")
    figure(doc, FIG / "console-03-lint.png", 14.0,
           "Console 3 — The static analysis gate. ruff reports no findings; bandit reports no "
           "issues at medium severity or above.")

    h2(doc, "9.4  API behaviour, logs and metrics")
    figure(doc, FIG / "console-07a-api-session.png", 12.6,
           "Console 4 — A real session against the running server, part 1. Note the 674 ms "
           "registration — that is PBKDF2 doing its job — against 5.9 ms for the authenticated "
           "read that follows it.")
    figure(doc, FIG / "console-07b-api-session.png", 12.6,
           "Console 5 — Part 2, the failure paths: 409 on the duplicate booking, 401 without a "
           "token, 403 for a patient calling an admin route, and 200 for the same route as admin.")
    figure(doc, FIG / "console-08-json-logs.png", 16.2,
           "Console 6 — Structured logs for that session. Read the three highlighted lines in "
           "order: the booking is logged at 34.95 ms, the event is published, and only then is "
           "the notification queued. That ordering is the event-driven design working.")
    figure(doc, FIG / "console-09-metrics.png", 12.4,
           "Console 7 — Live counters. The 429s are real: our own load test tripped the login "
           "rate limiter, which is the limiter passing its field test.")

    h2(doc, "9.5  Version control and the delivery pipeline")
    figure(doc, FIG / "console-04-git.png", 14.6,
           "Console 8 — Commit history and remote. 58 tracked files.")
    figure(doc, FIG / "console-05-cicd.png", 14.6,
           "Console 9 — A complete pipeline run: static analysis, tests, container build and "
           "gated deployment, all green.")
    figure(doc, FIG / "console-06-docker-ci.png", 15.0,
           "Console 10 — The multi-stage image being built on a clean runner and then smoke-tested: "
           "the container is started and answers /health with `\"status\":\"UP\"` before the stage "
           "is accepted.")

    h2(doc, "9.6  When the pipeline said no")
    para(doc, "Two of our commits were rejected by our own pipeline, and we think that is the "
              "most convincing evidence in this section. The first push failed static analysis "
              "because ruff flagged FastAPI's `Depends()` dependency-injection idiom under rule "
              "B008. That is a genuine false positive for this framework, so the fix was not to "
              "silence the tool blindly but to add a project lint configuration that documents "
              "precisely which two rules are disabled and why. The second push failed the deploy "
              "stage: our staging command was written as a YAML plain scalar containing an inline "
              "`#`, which truncated the shell line and left an unterminated quote. Rewriting it "
              "as a block scalar fixed it.")
    para(doc, "Neither defect would have been caught by reading the code. Both were caught in "
              "under two minutes by automation, which is the entire argument for having it.")
    link_para(doc, "The green run shown in Console 9", RUN_URL)
    link_para(doc, "Full run history, failures included", REPO + "/actions")


# =========================================================== section 10
def section10(doc):
    h1(doc, "10.  Results and Validation", page_break=True)

    h2(doc, "10.1  How we measured")
    para(doc, "A closed-loop harness runs a pool of worker threads issuing requests continuously "
              "for eight seconds per scenario, recording the latency of every individual request "
              "so that percentiles can be reported rather than a mean that hides the tail. "
              "Connections are pooled, as a browser or gateway would pool them. All figures below "
              "come from one run against the application on a Windows 11 laptop; the raw data is "
              "in the repository as `docs/loadtest-results.json`.")

    note(doc, "**The measurement bug that nearly went into this report.** Our first run reported "
              "2 050 ms for every scenario, at every level of concurrency. A flat number that "
              "does not move when you change the load is not a performance result, it is a "
              "constant, so we went looking for it. On Windows, `localhost` resolves to the IPv6 "
              "address `::1` first, and uvicorn was bound to IPv4 only, so every connection spent "
              "about two seconds failing over. Addressing the server as `127.0.0.1` and reusing "
              "connections gave the real figures — around 1.5 ms. We very nearly published the "
              "wrong ones, and the only reason we did not is that the numbers were too uniform to "
              "believe.")

    h2(doc, "10.2  Throughput and latency")
    figure(doc, FIG / "fig7-performance.png", 16.4,
           "Figure 7 — Measured throughput and latency percentiles against concurrency. Throughput "
           "peaks at 461.7 rps with five workers and then falls as contention grows, which is the "
           "signature of a CPU-bound single process. The p99 at fifty concurrent users is 263 ms, "
           "still comfortably inside the 500 ms budget.")
    table(doc,
          ["Concurrency", "Requests", "Throughput (rps)", "p50 (ms)", "p95 (ms)", "p99 (ms)", "Success"],
          [["1", "2 546", "318.2", "2.98", "3.88", "4.45", "100%"],
           ["5", "3 695", "**461.7**", "9.73", "13.80", "19.91", "100%"],
           ["10", "3 447", "430.2", "20.26", "27.65", "38.15", "100%"],
           ["25", "2 959", "368.7", "50.15", "68.33", "86.94", "100%"],
           ["50", "2 114", "262.3", "101.62", "200.39", "263.21", "100%"]],
          widths=[13, 13, 17, 13, 13, 13, 12], size=8.5,
          align_center=(0, 1, 2, 3, 4, 5, 6))
    para(doc, "Reading this table taught us something we had assumed away. Throughput does not "
              "increase indefinitely with concurrency; it peaks at five workers and then declines "
              "while latency keeps climbing. That is the classic behaviour of a single CPU-bound "
              "process, and it tells us the scaling strategy has to be horizontal — more "
              "replicas behind a load balancer, which the stateless JWT design already permits — "
              "rather than simply pushing more traffic at one instance.")

    figure(doc, FIG / "fig8-endpoint-throughput.png", 16.4,
           "Figure 8 — Throughput by endpoint at 25 concurrent users. The slots endpoint is the "
           "slowest read at 164 rps because it filters and orders a much larger table; it is the "
           "first place we would add an index if traffic grew.")

    h2(doc, "10.3  What security costs")
    figure(doc, FIG / "fig9-crypto-cost.png", 9.4,
           "Figure 9 — Cost of the security primitives, log scale. PBKDF2 verification takes "
           "246 ms; JWT verification takes 0.007 ms — roughly 35 000 times cheaper.")
    para(doc, "This chart is the justification for the whole session design. Deriving a password "
              "hash is expensive **on purpose**: 600 000 rounds is what makes an offline attack on "
              "a stolen database impractical. But if we paid that cost on every request the system "
              "would manage about four requests per second. Verifying a signed token instead costs "
              "seven microseconds. Paying 246 ms once at login and 0.007 ms on every subsequent "
              "request is the trade that makes the system both secure and usable, and it is "
              "visible in Console 4: registration took 674 ms, the authenticated read that "
              "followed took 5.9 ms.")

    h2(doc, "10.4  Validation against the requirements")
    table(doc,
          ["Requirement", "Target", "Measured", "Verdict"],
          [["NFR-01 Performance", "p95 < 500 ms at 25 users", "68.33 ms", "Met, 7× margin"],
           ["NFR-02 Responsiveness", "Notification off the request path", "Logged after the 201 response", "Met"],
           ["NFR-03 Scalability", "Throughput rises until CPU-bound", "318 → 462 rps; ceiling identified", "Met, and quantified"],
           ["NFR-04 Reliability", "No failed requests under load", "36 057 requests, 0 failures", "Met"],
           ["NFR-05 Data integrity", "One slot, one appointment", "10-thread race: 1 × 201, 9 × 409", "Met"],
           ["NFR-06 Security", "No plaintext, signed sessions, headers", "PBKDF2 600k; HS256; 3 headers", "Met"],
           ["NFR-07 Maintainability", "Clean static analysis, > 90% coverage", "ruff and bandit clean; 95%", "Met"],
           ["NFR-08 Operability", "Probes and metrics", "`/health`, `/ready`, `/metrics` live", "Met"],
           ["NFR-09 Portability", "Identical on laptop and runner", "Same image healthy in both", "Met"],
           ["NFR-10 Auditability", "Actions attributable", "`audit_log` written in-transaction", "Met"]],
          widths=[22, 27, 32, 19], size=8.5)
    para(doc, "All ten non-functional requirements are met, and all thirteen functional "
              "requirements have a passing test or a screenshot behind them. We want to be careful "
              "about what that does and does not prove: it establishes that the system meets the "
              "targets **we** set, on **one** machine, at the scale we tested. It does not "
              "establish behaviour at hospital scale, which would need a multi-instance "
              "deployment against PostgreSQL. Section 13 is honest about that gap.")


# =========================================================== section 11
def section11(doc):
    h1(doc, "11.  Analysis, Comparison, Trade-offs and Justification")

    h2(doc, "11.1  Architecture")
    table(doc,
          ["Option", "Advantages", "Limitations", "Verdict"],
          [["Layered monolith",
            "Simplest to build, deploy and reason about; one transaction boundary",
            "Module boundaries erode without discipline; scales only as one unit",
            "Rejected — no seam for later extraction"],
           ["**Modular monolith (chosen)**",
            "Real bounded contexts and one deployable; strong consistency stays free; a service can be extracted later without rewriting callers",
            "Still one scaling unit; a runaway module can affect its neighbours",
            "**Chosen** — the honest fit for four modules and this team"],
           ["Microservices",
            "Independent scaling and deployment; strong fault isolation",
            "Network hops, distributed transactions, four pipelines, far more operational surface",
            "Rejected — costs are real now, benefits arrive at a scale we do not have"],
           ["Serverless functions",
            "Scales to zero; no servers to manage",
            "Cold starts hurt interactive booking; per-invocation database connections are hostile to a relational store",
            "Rejected — wrong shape for a stateful transactional workload"]],
          widths=[16, 30, 32, 22], size=8.2)

    h2(doc, "11.2  Concurrency control — the decision that mattered most")
    table(doc,
          ["Strategy", "Behaviour under a ten-thread race", "Assessment"],
          [["Application-level check only",
            "Multiple threads pass the `is_booked` check before any writes; several bookings are created",
            "Rejected. A check-then-act sequence in application code is a race by construction"],
           ["Optimistic version column",
            "One writer wins, the rest retry; correct, but the retry loop is ours to write and get right",
            "Viable, and preferable at very high write contention"],
           ["**Row lock + UNIQUE constraint (chosen)**",
            "**Exactly one 201, nine 409s, measured in TC-16**",
            "**Chosen.** The database enforces the invariant, so no application path can bypass it"],
           ["Serialisable isolation everywhere",
            "Correct, but serialises unrelated transactions as well",
            "Rejected — a global cost for a local problem"]],
          widths=[20, 43, 37], size=8.3)

    h2(doc, "11.3  Data store and deployment")
    table(doc,
          ["Dimension", "Chosen", "Alternatives considered", "Reasoning"],
          [["Database", "SQLite via SQLAlchemy",
            "PostgreSQL, MySQL, MongoDB",
            "Zero setup for a reviewer, and the ORM keeps the migration to PostgreSQL to a `DATABASE_URL` change. MongoDB was rejected outright: our core invariant is a uniqueness constraint across related rows, which is precisely what a relational engine is for"],
           ["Messaging", "In-process event bus",
            "RabbitMQ, Kafka, Redis Streams",
            "A broker is the right production answer, but it would have added infrastructure we could not host. The interface is broker-shaped, so substitution touches one file"],
           ["Sessions", "Stateless HS256 JWT",
            "Server-side sessions, RS256",
            "Stateless tokens allow horizontal scaling with no shared session store. RS256 becomes worthwhile once several services must verify tokens without sharing a secret"],
           ["Deployment", "Docker image, compose locally",
            "Bare metal, Kubernetes",
            "Containers gave us laptop/CI parity immediately. Kubernetes is the natural next step and the probes we already expose are exactly what it consumes"]],
          widths=[13, 17, 18, 52], size=8.2)

    h2(doc, "11.4  Justification of the final solution")
    para(doc, "The selected solution is a containerised, API-first modular monolith with "
              "event-driven notification, database-enforced booking integrity and a gated CI/CD "
              "pipeline. We chose it because it answers each of the four problems identified in "
              "Section 1.1 with a mechanism rather than an intention: double booking is prevented "
              "by a constraint the application cannot bypass; throughput is protected by moving "
              "slow work off the request path; availability is made observable through probes and "
              "metrics that an orchestrator can act on; and integration is made possible by "
              "publishing a generated contract instead of hiding behaviour behind screens.")
    para(doc, "It is also the solution we can defend on cost. Every component is open source, the "
              "infrastructure bill was zero, and the operational burden is one process and one "
              "database. The main thing we gave up is independent scaling of the four modules, and "
              "the measurements in Section 10 tell us when that will start to matter: throughput "
              "peaks at 462 requests per second per instance, so the first response to growth is "
              "additional replicas, not a rewrite.")


# =========================================================== section 12
def section12(doc):
    h1(doc, "12.  Broader Considerations and SDG Relevance")

    h2(doc, "12.1  Privacy and patient data")
    para(doc, "Appointment data is medical data by implication: knowing that someone booked an "
              "oncologist reveals something even if no diagnosis is stored. We therefore collect "
              "only what a booking needs, scope every read to the authenticated principal so one "
              "patient cannot enumerate another's history, and write an append-only audit entry "
              "inside the same transaction as the action it records, so the trail cannot silently "
              "diverge from what happened. No real patient data was used at any point; every "
              "doctor and patient in the screenshots is fictional and seeded by `seed.py`.")

    h2(doc, "12.2  Ethics and accessibility")
    para(doc, "Two ethical points came up in discussion and changed the code. First, an "
              "appointment system allocates a scarce public resource, so it must not quietly "
              "advantage the technically confident: bookings are first-come-first-served with no "
              "hidden priority, and the conflict message says plainly that the slot has gone "
              "rather than failing ambiguously. Second, monitoring must be proportionate — our "
              "logs deliberately carry a correlation ID and a route template, not request bodies, "
              "so operational visibility does not become surveillance of what patients searched "
              "for. On accessibility, the interface uses semantic HTML with labelled form "
              "controls and text contrast above the WCAG AA threshold, though we note in Section "
              "13 that we have not tested it with a screen reader and cannot claim conformance.")

    h2(doc, "12.3  Economic and environmental considerations")
    para(doc, "The entire stack is open source and the infrastructure cost of building this was "
              "zero, which matters for public healthcare providers who cannot spend on licences. "
              "Environmentally, the honest observation is that efficiency is sustainability: a "
              "multi-stage build that discards the compiler toolchain produces a much smaller "
              "image to store and transfer, dependency-free metrics and JWT code keep the runtime "
              "small, and an application answering a read in three milliseconds burns far less "
              "energy per booking than one taking three hundred. We did not measure power draw "
              "and will not pretend otherwise.")

    h2(doc, "12.4  SDG relevance")
    table(doc,
          ["Goal", "Connection", "What in this project supports the claim"],
          [["**SDG 3** — Good Health and Well-being",
            "Reduces the friction between a patient and timely care",
            "Self-service booking removes the phone queue; guaranteed-unique slots remove the double-booked appointment that wastes a consultation"],
           ["**SDG 9** — Industry, Innovation and Infrastructure",
            "Builds resilient, integrable digital infrastructure",
            "API-first design with a published contract; container images and health probes that an orchestrator can manage"],
           ["**SDG 10** — Reduced Inequalities",
            "Equal access to appointment slots",
            "First-come-first-served allocation with no hidden prioritisation, and a responsive interface usable on a low-cost phone"],
           ["**SDG 12** — Responsible Consumption",
            "Efficient use of computing resources",
            "Slim runtime image, minimal dependency tree, measured low CPU cost per request"]],
          widths=[20, 26, 54], size=8.4)

    h2(doc, "12.5  Professional responsibility")
    para(doc, "We have tried to hold this report to the same standard as the code. Where a number "
              "was wrong we said so and explained how we found out — the 2 050 ms measurement "
              "artefact in Section 10.1 and the inflated coverage figure in Section 8.3 are both "
              "reported rather than quietly corrected. Where evidence is weaker than it looks, we "
              "have said that too: the container evidence comes from CI rather than a local "
              "terminal, and our load testing was single-machine. Reporting only the flattering "
              "half of a result is the easiest form of professional dishonesty in engineering, "
              "and it is the one we were most concerned to avoid.")


# =========================================================== section 13-16
def section13(doc):
    h1(doc, "13.  Conclusion, Limitations and Possible Improvements")

    h2(doc, "13.1  Conclusion")
    para(doc, "We set out to build a healthcare appointment platform that books a slot exactly "
              "once, keeps slow work off the patient's response, exposes its behaviour as a "
              "documented API and reports its own health. All four hold, and each is backed by "
              "evidence rather than assertion: a ten-thread race producing exactly one "
              "confirmation, structured logs showing the notification written after the response, "
              "a generated OpenAPI document covering every route, and a container built on a "
              "clean runner that answers its own health probe. Twenty-five automated tests cover "
              "95% of the application code and run on every push through a four-stage pipeline "
              "that has already rejected two of our own commits.")
    para(doc, "The single most valuable thing we learned is smaller than the architecture and "
              "more useful: correctness properties belong where they cannot be bypassed. Our "
              "booking code checks whether a slot is taken, but that check is only an "
              "optimisation. The guarantee lives in a `UNIQUE` constraint, because that is the one "
              "place no code path, present or future, can go around.")

    h2(doc, "13.2  Limitations")
    table(doc,
          ["Limitation", "Why it exists", "Consequence for a real deployment"],
          [["SQLite serialises writers", "Chosen for zero-setup reproducibility", "A write-throughput ceiling; PostgreSQL needed before real load"],
           ["The event bus is in-process", "No broker infrastructure available to us", "Undelivered events are lost if the process dies; needs a durable broker"],
           ["Load tested on one machine", "No cluster available", "Multi-instance behaviour and database contention are unmeasured"],
           ["Notifications are in-app only", "E-mail and SMS need paid gateways", "Patients are not reached outside the application"],
           ["No screen-reader testing", "No assistive technology available to us", "Accessibility conformance cannot be claimed, only intended"],
           ["Single JWT lifetime, no refresh", "Kept the auth surface small", "A one-hour session with no silent renewal"],
           ["Coverage misses defensive branches", "Some require breaking a dependency deliberately", "The database-down readiness path is untested"]],
          widths=[24, 30, 46], size=8.4)

    h2(doc, "13.3  Possible improvements, in the order we would do them")
    table(doc,
          ["#", "Improvement", "Why this order"],
          [["1", "Move to PostgreSQL and add a composite index on `slots(doctor_id, start_at, is_booked)`",
            "Removes the write ceiling and targets the slowest endpoint we measured (164 rps)"],
           ["2", "Replace the in-process bus with RabbitMQ",
            "Makes notification delivery survive a process restart; the interface already matches"],
           ["3", "Add refresh tokens and revocation",
            "Improves the session experience without weakening the security model"],
           ["4", "E-mail and SMS notification channels",
            "The `channel` column and subscriber model already anticipate this"],
           ["5", "Deploy to Kubernetes with an HPA driven by our metrics",
            "The probes and Prometheus series it needs are already exposed"],
           ["6", "Screen-reader and keyboard-navigation audit",
            "Turns an accessibility intention into a verified claim"],
           ["7", "Doctor-facing console and rescheduling",
            "The largest missing user-facing capability, and it needs the items above first"]],
          widths=[4, 40, 56], size=8.4, align_center=(0,))


def section14(doc):
    h1(doc, "14.  Individual Contribution of Group Members")
    para(doc, "We worked in Scrum with shared ownership, so no module belonged to one person "
              "exclusively; every change was reviewed by at least one other member before merge. "
              "The table records primary responsibility. Replace the bracketed names before "
              "submission.")
    table(doc,
          ["Member", "Primary responsibility", "Specific contributions", "Sections"],
          [["[Student Name 1]\n[Register No.]", "Architecture and backend core",
            "Domain model and schema constraints; booking transaction and concurrency control; event bus; API design",
            "1, 4, 5, 6, 11"],
           ["[Student Name 2]\n[Register No.]", "Security and authentication",
            "PBKDF2 password storage; JWT issue and verification; role guard; rate limiter; the crypto benchmark",
            "3, 5.6, 6.2, 10.3"],
           ["[Student Name 3]\n[Register No.]", "Quality assurance and performance",
            "The 25-test suite including the ten-thread race; coverage configuration; load-test harness and charts",
            "8, 10"],
           ["[Student Name 4]\n[Register No.]", "DevOps, frontend and documentation",
            "Multi-stage Dockerfile; four-stage GitHub Actions pipeline; patient portal; screenshot automation; this report",
            "7, 9, 12, 13"]],
          widths=[16, 22, 47, 15], size=8.4)
    para(doc, "Contribution is independently visible in the repository history at "
              "`" + REPO + "/commits/main`, where every commit message states what changed and why.",
         space_after=3)


def section15(doc):
    h1(doc, "15.  References")
    refs = [
        "Sommerville, I. (2016) *Software Engineering*, 10th edn. Pearson Education.",
        "Pressman, R. S. and Maxim, B. R. (2020) *Software Engineering: A Practitioner's Approach*, 9th edn. McGraw-Hill.",
        "Newman, S. (2021) *Building Microservices: Designing Fine-Grained Systems*, 2nd edn. O'Reilly Media.",
        "Kleppmann, M. (2017) *Designing Data-Intensive Applications*. O'Reilly Media. (Chapters 7 and 9 on transactions and consistency.)",
        "Richardson, C. (2018) *Microservices Patterns*. Manning Publications.",
        "Forsgren, N., Humble, J. and Kim, G. (2018) *Accelerate: The Science of Lean Software and DevOps*. IT Revolution Press.",
        "Fowler, M. (2019) 'Bounded Context', martinfowler.com. Available at: https://martinfowler.com/bliki/BoundedContext.html",
        "OWASP Foundation (2024) *Password Storage Cheat Sheet*. Available at: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html",
        "OWASP Foundation (2021) *OWASP Top 10:2021*. Available at: https://owasp.org/Top10/",
        "Jones, M., Bradley, J. and Sakimura, N. (2015) *RFC 7519: JSON Web Token (JWT)*. IETF. Available at: https://www.rfc-editor.org/rfc/rfc7519",
        "Jones, M., Bradley, J. and Sakimura, N. (2015) *RFC 7515: JSON Web Signature (JWS)*. IETF.",
        "Moriarty, K., Kaliski, B. and Rusch, A. (2017) *RFC 8018: PKCS #5 Password-Based Cryptography Specification v2.1*. IETF.",
        "Fielding, R. and Reschke, J. (2014) *RFC 7231: HTTP/1.1 Semantics and Content*. IETF. (Status code semantics, including 409 Conflict.)",
        "Ramírez, S. (2024) *FastAPI Documentation*. Available at: https://fastapi.tiangolo.com/",
        "SQLAlchemy Project (2024) *SQLAlchemy 2.0 Documentation*. Available at: https://docs.sqlalchemy.org/en/20/",
        "Pydantic (2024) *Pydantic V2 Documentation*. Available at: https://docs.pydantic.dev/latest/",
        "OpenAPI Initiative (2021) *OpenAPI Specification v3.1.0*. Available at: https://spec.openapis.org/oas/v3.1.0",
        "Docker Inc. (2024) *Best practices for writing Dockerfiles*. Available at: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/",
        "Prometheus Authors (2024) *Exposition Formats*. Available at: https://prometheus.io/docs/instrumenting/exposition_formats/",
        "GitHub (2024) *GitHub Actions Documentation*. Available at: https://docs.github.com/en/actions",
        "Kubernetes Authors (2024) *Configure Liveness, Readiness and Startup Probes*. Available at: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/",
        "W3C (2023) *Web Content Accessibility Guidelines (WCAG) 2.2*. Available at: https://www.w3.org/TR/WCAG22/",
        "United Nations (2015) *Transforming our world: the 2030 Agenda for Sustainable Development*. Available at: https://sdgs.un.org/2030agenda",
        "Beck, K. et al. (2001) *Manifesto for Agile Software Development*. Available at: https://agilemanifesto.org/",
        "Schwaber, K. and Sutherland, J. (2020) *The Scrum Guide*. Available at: https://scrumguides.org/",
    ]
    bullets(doc, refs, size=Pt(8.6), numbered=True)

    h2(doc, "AI-assisted tools declaration")
    para(doc, "An AI coding assistant (Anthropic Claude, accessed through Claude Code) was used "
              "during development for code review, for drafting boilerplate, and for assistance "
              "in preparing this document. All architectural decisions, all trade-off judgements "
              "and all conclusions are our own. Every measurement, screenshot, test result and "
              "log line reproduced here was generated by executing our code, and each is "
              "reproducible from the public repository.", space_after=3)


def section16(doc):
    h1(doc, "16.  One-Page Individual Reflection", page_break=True)
    para(doc, "*Each team member completes one copy of this page independently. The text below is "
              "a completed example written by one member; the prompts in each heading indicate "
              "what to cover.*", italic=True, space_after=6)

    h2(doc, "Reflection — [Student Name 1], [Register No.]")

    para(doc, "**Design and development decisions I contributed to.** The decision I argued for "
              "hardest, and the one I got wrong first, was how to stop two patients booking the "
              "same slot. My initial implementation read the slot, checked `is_booked`, and then "
              "wrote the appointment. It looked obviously correct to me, and it passed the test I "
              "wrote for it. What I had actually written was a check-then-act race: nothing "
              "prevents a second request reading the same row between my check and my write. The "
              "fix was to stop treating this as an application problem at all and put a `UNIQUE` "
              "constraint on `appointments.slot_id`, so the database refuses the second write no "
              "matter what any code does. I now think of the application-level check as a "
              "performance optimisation and the constraint as the actual guarantee, which is a "
              "distinction I did not have language for before this assignment.")

    para(doc, "**Challenges I faced.** The hardest hour of the project was discovering that our "
              "concurrency test had been passing for the wrong reason. Our fixture shared a "
              "single database session across all ten threads, so they were never truly "
              "concurrent, and the test was asserting a property it could not actually observe. "
              "When we fixed the fixture the test failed loudly with a session-state error, and "
              "my first instinct was to make the error go away. Talking it through with the team, "
              "we realised the failure was the point: the test had finally become capable of "
              "detecting the bug it existed to catch. A second, humbler challenge was our "
              "performance measurement reporting exactly 2 050 ms for every scenario. I wanted to "
              "believe it, because the number looked precise. It turned out to be an IPv6 "
              "resolution fallback on `localhost` and had nothing to do with our code.")

    para(doc, "**What I learned.** Three things I expect to keep. First, put invariants where they "
              "cannot be bypassed; a rule enforced by the storage engine survives every future "
              "refactor, and a rule enforced by a comment does not. Second, a green test proves "
              "nothing until you have watched it go red for the right reason — I now deliberately "
              "break the mechanism a test guards to confirm the test notices. Third, be "
              "suspicious of measurements that are too tidy; a latency figure that does not change "
              "when you change the load is telling you about your instrument, not your system.")

    para(doc, "**SDG connection.** The work relates most directly to **SDG 3, Good Health and "
              "Well-being**. Removing the telephone queue between a patient and an appointment "
              "lowers a real barrier to timely care, and eliminating double bookings prevents a "
              "consultation slot being wasted on a scheduling error while another patient waits. "
              "There is a secondary connection to **SDG 9**, since an API-first, containerised "
              "service is the kind of resilient digital infrastructure a public health system can "
              "actually maintain and extend, and to **SDG 10**, because strictly "
              "first-come-first-served allocation with no hidden prioritisation treats every "
              "patient's request identically.")

    para(doc, "**Course outcome attainment.** For **CO1 and CO2** I moved from a plain-language "
              "problem statement to numbered functional and non-functional requirements and then "
              "to an architecture chosen against explicit alternatives, which is the part of "
              "software engineering I had previously skipped. **CO3** was met by implementing the "
              "system end to end and containerising it, so the design became something that "
              "actually runs rather than a diagram. **CO4** was met through the twenty-five test "
              "cases, the coverage measurement and the load testing that turned \"it feels fast\" "
              "into p50, p95 and p99 figures I can defend. **CO5** was met by comparing "
              "architectural and deployment alternatives honestly, including the ones we rejected, "
              "and by documenting the limitations of what we built instead of only its strengths.")

    doc.add_paragraph()
    para(doc, "Signature: ______________________          Date: ______________",
         justify=False, space_after=2)
